# Server Configuration
server.port=9999

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Database Configuration - Aiven MySQL
spring.datasource.url=jdbc:mysql://mysql-2a3f0478-gracypatel2446-885e.a.aivencloud.com:15717/defaultdb?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_QtrVWdVhJDeUDYEazz3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.grownited.eauction=DEBUG
